### ISSUE TITLE
with clean clone dist folder is missing and npm run build fails.

### ISSUE THREAD

**Issue by ilkkanisula** [pouchdb/pouchbase#46]
Workaround:
Create the dist folder manually.
e.g. mkdir dist

**Comment by BigBlueHat** [comment]
Yeah. I found the same in #47 

@daleharvey mind taking a quick look? :smile:

**Comment by daleharvey** [comment]
So yeh I decided a while ago that the current way pouchbase works is not particularly sustainable for me to maintain as a side project, I am gonna reuse the domain and put up a test bed for pouchdb to replicate with that gets wiped every night or so. For things that look similiar to what pouch.host / pouchbase was bug @janl for another possible project :)

**Comment by daleharvey** [comment]
Updated the README and will delete the repo in a week or so, give people time to fork if they want to https://github.com/pouchdb/pouchbase/blob/master/README.md

**Comment by BigBlueHat** [comment]
@daleharvey why delete it?

@janl would love to hear what you've got on this front? :smile_cat:

**Comment by daleharvey** [comment]
Since it will be a little confusing if I using pouchbase for another project to have this one with the same name, I dont think theres much value in this code without it being used and if anyone else wants to use it they can fork

**Comment by BigBlueHat** [comment]
k. Works for me. I just hate to see more URLs die. :stuck_out_tongue: 

Maybe name it back to pouch.host / janus? or...delete it. **/me** updates fork.

**Comment by janl** [comment]
👀
